"""initial opendata schema with UUID

Revision ID: 65c4949bf4df
Revises: 
Create Date: 2026-01-07 22:41:45.929835+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65c4949bf4df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetcher',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='opendata'
    )
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('project', sa.String(length=50), nullable=False),
    sa.Column('fetcher_id', sa.UUID(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fetcher_id'], ['opendata.fetcher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='opendata'
    )
    op.create_table('type_fetcher_params',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fetcher_id', sa.UUID(), nullable=False),
    sa.Column('param_name', sa.String(length=100), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['fetcher_id'], ['opendata.fetcher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='opendata'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type_fetcher_params', schema='opendata')
    op.drop_table('source', schema='opendata')
    op.drop_table('fetcher', schema='opendata')
    # ### end Alembic commands ###
