"""Auditoría (AuditMixin) en todos los modelos + huella de identidad de Resource + cuota de refrescos.

- Añade created_at/updated_at/created_by_id/updated_by_id a todas las tablas de dominio.
- Resource: params_hash (huella de identidad, único) con backfill dedup-first-wins.
- Usuario: cuota_refrescos_diaria.
- Nueva tabla refresco_extemporaneo (ledger de refrescos a demanda para cuota/auditoría).
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import hashlib, json

revision = 'a2b3c4d5e6f8'
down_revision = 'e1f2a3b4c5d7'
branch_labels = None
depends_on = None

SCHEMA = "opendata"

def _huella(pairs):
    norm = sorted(((str(k), "" if v is None else str(v)) for k, v in pairs), key=lambda kv: kv[0])
    return hashlib.sha256(json.dumps(norm, ensure_ascii=False, separators=(",", ":")).encode("utf-8")).hexdigest()

def upgrade():
    bind = op.get_bind()
    insp = sa.inspect(bind)
    _cache = {}
    def _cols(table):
        if table not in _cache:
            try:
                _cache[table] = {c["name"] for c in insp.get_columns(table, schema=SCHEMA)}
            except Exception:
                _cache[table] = set()
        return _cache[table]
    def _add(table, col, schema=SCHEMA):
        # idempotente: 0001 ya creo created_at en varias tablas; no re-añadir.
        if col.name in _cols(table):
            return
        op.add_column(table, col, schema=schema)
        _cache[table].add(col.name)
    _add("app_config", sa.Column("created_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("app_config", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("app_config", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("application", sa.Column("created_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("application", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("application", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("application", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("application_notification", sa.Column("created_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("application_notification", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("application_notification", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("application_notification", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("dataset", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("dataset", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("dataset", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("dataset_lease", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("dataset_lease", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("dataset_lease", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("dataset_subscription", sa.Column("created_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("dataset_subscription", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("dataset_subscription", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("dataset_subscription", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("derived_dataset_config", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("derived_dataset_config", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("derived_dataset_config", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("derived_dataset_entry", sa.Column("created_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("derived_dataset_entry", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("derived_dataset_entry", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("evento", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("evento", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("evento", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("fetcher", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("fetcher", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("fetcher", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("fetcher_preset", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("fetcher_preset", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("fetcher_preset", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("field_metadata", sa.Column("created_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("field_metadata", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("field_metadata", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("field_metadata", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("funcionalidad", sa.Column("created_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("funcionalidad", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("funcionalidad", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("funcionalidad", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("publisher", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("publisher", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("publisher", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("resource", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("resource", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("resource", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("resource_candidate", sa.Column("created_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("resource_candidate", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("resource_candidate", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("resource_candidate", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("resource_dependency", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("resource_dependency", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("resource_dependency", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("resource_execution", sa.Column("created_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("resource_execution", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("resource_execution", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("resource_execution", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("resource_manifest_version", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("resource_manifest_version", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("resource_manifest_version", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("resource_param", sa.Column("created_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("resource_param", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("resource_param", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("resource_param", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("rol", sa.Column("created_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("rol", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("rol", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("rol", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("sesion", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("sesion", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("sesion", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("type_fetcher_params", sa.Column("created_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("type_fetcher_params", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("type_fetcher_params", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("type_fetcher_params", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("usuario", sa.Column("updated_at", sa.DateTime(), nullable=True), schema=SCHEMA)
    _add("usuario", sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    _add("usuario", sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True), schema=SCHEMA)
    # Resource: huella de identidad (params_hash)
    _add("resource", sa.Column("params_hash", sa.String(length=64), nullable=True), schema=SCHEMA)
    op.create_index("ix_resource_params_hash", "resource", ["params_hash"], schema=SCHEMA)
    # Backfill: calcula la huella de cada recurso a partir de sus params (dedup first-wins).
    res = bind.execute(sa.text("SELECT id FROM opendata.resource WHERE deleted_at IS NULL ORDER BY created_at NULLS FIRST, id")).fetchall()
    vistos = set()
    for (rid,) in res:
        prs = bind.execute(sa.text("SELECT key, value FROM opendata.resource_param WHERE resource_id = :r"), {"r": rid}).fetchall()
        h = _huella([(k, v) for k, v in prs])
        if h in vistos:
            continue  # duplicado preexistente: se deja params_hash NULL (se deduplicará en adelante)
        vistos.add(h)
        bind.execute(sa.text("UPDATE opendata.resource SET params_hash = :h WHERE id = :r"), {"h": h, "r": rid})
    op.create_unique_constraint("uq_resource_params_hash", "resource", ["params_hash"], schema=SCHEMA)
    # Usuario: cuota diaria de refrescos a demanda
    _add("usuario", sa.Column("cuota_refrescos_diaria", sa.Integer(), nullable=False, server_default="50"), schema=SCHEMA)
    # Ledger de refrescos a demanda (cuota/auditoría)
    op.create_table("refresco_extemporaneo",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("resource_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.resource.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True),
        sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("opendata.usuario.id", ondelete="SET NULL"), nullable=True),
        schema=SCHEMA)
    op.create_index("ix_refresco_extemporaneo_created_by_id", "refresco_extemporaneo", ["created_by_id"], schema=SCHEMA)
    op.create_index("ix_refresco_extemporaneo_created_at", "refresco_extemporaneo", ["created_at"], schema=SCHEMA)
    op.create_index("ix_refresco_extemporaneo_resource_id", "refresco_extemporaneo", ["resource_id"], schema=SCHEMA)

def downgrade():
    op.drop_table("refresco_extemporaneo", schema=SCHEMA)
    op.drop_column("usuario", "cuota_refrescos_diaria", schema=SCHEMA)
    op.drop_constraint("uq_resource_params_hash", "resource", schema=SCHEMA, type_="unique")
    op.drop_index("ix_resource_params_hash", table_name="resource", schema=SCHEMA)
    op.drop_column("resource", "params_hash", schema=SCHEMA)
    op.drop_column("app_config", "updated_by_id", schema=SCHEMA)
    op.drop_column("app_config", "created_by_id", schema=SCHEMA)
    op.drop_column("app_config", "created_at", schema=SCHEMA)
    op.drop_column("application", "updated_by_id", schema=SCHEMA)
    op.drop_column("application", "created_by_id", schema=SCHEMA)
    op.drop_column("application", "updated_at", schema=SCHEMA)
    op.drop_column("application", "created_at", schema=SCHEMA)
    op.drop_column("application_notification", "updated_by_id", schema=SCHEMA)
    op.drop_column("application_notification", "created_by_id", schema=SCHEMA)
    op.drop_column("application_notification", "updated_at", schema=SCHEMA)
    op.drop_column("application_notification", "created_at", schema=SCHEMA)
    op.drop_column("dataset", "updated_by_id", schema=SCHEMA)
    op.drop_column("dataset", "created_by_id", schema=SCHEMA)
    op.drop_column("dataset", "updated_at", schema=SCHEMA)
    op.drop_column("dataset_lease", "updated_by_id", schema=SCHEMA)
    op.drop_column("dataset_lease", "created_by_id", schema=SCHEMA)
    op.drop_column("dataset_lease", "updated_at", schema=SCHEMA)
    op.drop_column("dataset_subscription", "updated_by_id", schema=SCHEMA)
    op.drop_column("dataset_subscription", "created_by_id", schema=SCHEMA)
    op.drop_column("dataset_subscription", "updated_at", schema=SCHEMA)
    op.drop_column("dataset_subscription", "created_at", schema=SCHEMA)
    op.drop_column("derived_dataset_config", "updated_by_id", schema=SCHEMA)
    op.drop_column("derived_dataset_config", "created_by_id", schema=SCHEMA)
    op.drop_column("derived_dataset_config", "updated_at", schema=SCHEMA)
    op.drop_column("derived_dataset_entry", "updated_by_id", schema=SCHEMA)
    op.drop_column("derived_dataset_entry", "created_by_id", schema=SCHEMA)
    op.drop_column("derived_dataset_entry", "created_at", schema=SCHEMA)
    op.drop_column("evento", "updated_by_id", schema=SCHEMA)
    op.drop_column("evento", "created_by_id", schema=SCHEMA)
    op.drop_column("evento", "updated_at", schema=SCHEMA)
    op.drop_column("fetcher", "updated_by_id", schema=SCHEMA)
    op.drop_column("fetcher", "created_by_id", schema=SCHEMA)
    op.drop_column("fetcher", "updated_at", schema=SCHEMA)
    op.drop_column("fetcher_preset", "updated_by_id", schema=SCHEMA)
    op.drop_column("fetcher_preset", "created_by_id", schema=SCHEMA)
    op.drop_column("fetcher_preset", "updated_at", schema=SCHEMA)
    op.drop_column("field_metadata", "updated_by_id", schema=SCHEMA)
    op.drop_column("field_metadata", "created_by_id", schema=SCHEMA)
    op.drop_column("field_metadata", "updated_at", schema=SCHEMA)
    op.drop_column("field_metadata", "created_at", schema=SCHEMA)
    op.drop_column("funcionalidad", "updated_by_id", schema=SCHEMA)
    op.drop_column("funcionalidad", "created_by_id", schema=SCHEMA)
    op.drop_column("funcionalidad", "updated_at", schema=SCHEMA)
    op.drop_column("funcionalidad", "created_at", schema=SCHEMA)
    op.drop_column("publisher", "updated_by_id", schema=SCHEMA)
    op.drop_column("publisher", "created_by_id", schema=SCHEMA)
    op.drop_column("publisher", "updated_at", schema=SCHEMA)
    op.drop_column("resource", "updated_by_id", schema=SCHEMA)
    op.drop_column("resource", "created_by_id", schema=SCHEMA)
    op.drop_column("resource", "updated_at", schema=SCHEMA)
    op.drop_column("resource_candidate", "updated_by_id", schema=SCHEMA)
    op.drop_column("resource_candidate", "created_by_id", schema=SCHEMA)
    op.drop_column("resource_candidate", "updated_at", schema=SCHEMA)
    op.drop_column("resource_candidate", "created_at", schema=SCHEMA)
    op.drop_column("resource_dependency", "updated_by_id", schema=SCHEMA)
    op.drop_column("resource_dependency", "created_by_id", schema=SCHEMA)
    op.drop_column("resource_dependency", "updated_at", schema=SCHEMA)
    op.drop_column("resource_execution", "updated_by_id", schema=SCHEMA)
    op.drop_column("resource_execution", "created_by_id", schema=SCHEMA)
    op.drop_column("resource_execution", "updated_at", schema=SCHEMA)
    op.drop_column("resource_execution", "created_at", schema=SCHEMA)
    op.drop_column("resource_manifest_version", "updated_by_id", schema=SCHEMA)
    op.drop_column("resource_manifest_version", "created_by_id", schema=SCHEMA)
    op.drop_column("resource_manifest_version", "updated_at", schema=SCHEMA)
    op.drop_column("resource_param", "updated_by_id", schema=SCHEMA)
    op.drop_column("resource_param", "created_by_id", schema=SCHEMA)
    op.drop_column("resource_param", "updated_at", schema=SCHEMA)
    op.drop_column("resource_param", "created_at", schema=SCHEMA)
    op.drop_column("rol", "updated_by_id", schema=SCHEMA)
    op.drop_column("rol", "created_by_id", schema=SCHEMA)
    op.drop_column("rol", "updated_at", schema=SCHEMA)
    op.drop_column("rol", "created_at", schema=SCHEMA)
    op.drop_column("sesion", "updated_by_id", schema=SCHEMA)
    op.drop_column("sesion", "created_by_id", schema=SCHEMA)
    op.drop_column("sesion", "updated_at", schema=SCHEMA)
    op.drop_column("type_fetcher_params", "updated_by_id", schema=SCHEMA)
    op.drop_column("type_fetcher_params", "created_by_id", schema=SCHEMA)
    op.drop_column("type_fetcher_params", "updated_at", schema=SCHEMA)
    op.drop_column("type_fetcher_params", "created_at", schema=SCHEMA)
    op.drop_column("usuario", "updated_by_id", schema=SCHEMA)
    op.drop_column("usuario", "created_by_id", schema=SCHEMA)
    op.drop_column("usuario", "updated_at", schema=SCHEMA)

